### ISSUE TITLE
The operating time of the miner

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/UnamWebPanel#116]
Is it possible to add data to the panel for the total number of miner operating time? 
By type, how many days and hours the miner works

It will be convenient to analyze the life of miners in general

**Comment by UnamSanctam** [comment]
You mean how long it's been since that miner session was started or how long it's been since it was installed? I'm adding the run time in the next update (and I'm guessing that's what you mean), and you can see the creation time (first connect) in the database if that's what you want.

**Comment by anbu-squad** [comment]
Yes, right! =)

1. The period from the date of installation
and
2. How much time was spent on the mining session

I personally check online at this time through the search by entering the date and time

It is convenient to check and observe the behavior of bots through the search

In the panel through the search, you can see:
- constant rotation of miners throughout the day
- and intervals of work from hours to days

Based on this, I just want to understand how many "days have lived" in the period from the date of installation

**Comment by UnamSanctam** [comment]
Well in the next version there will be a "Run Time" field but it only counts the current mining session (since it's reported by the miner). And I could make the "Creation Time" field visible if it isn't already (think I hid it to reduce the number of fields). Though I'm currently not planning on adding a field for the total amount of run time combined during all sessions since it's a bit difficult/unreliable to implement, so I'd have to find some good solution for it first.
