### ISSUE TITLE
Got two questions

### ISSUE THREAD

**Issue by Werlrlivx** [UnamSanctam/UnamWebPanel#157]
1. Is the data some how encrypted (it doesnt seem so and if it is there are no custom encryption keys?)
2. Is there some sort of verification if a stub is real so no one can fabricate fake entries and flood your panel

**Comment by UnamSanctam** [comment]
1. No (other than SSL encryption if you use https) since that would cost a lot of performance, especially for those with over 100 000 miners. And there isn't really any private data anyways that you can't otherwise retrieve through sniffing the traffic.
2. No that wouldn't really be possible to do, you can never really truly verify a client since they can always just forge it (if they have your miner then they can just sniff the traffic to replicate it no matter what verification you have).

**Comment by Werlrlivx** [comment]
1. Ur absolutely right about i never thought about it in that way 
2. Ur absolutely right here too but there could be some sort of a password type thing that could compare the pass from the miner and the pass from the panel and deny any miner that has a different one but that would be pretty much useless since u could extract the config (or sniff data like u said) containing that pass and just using it (could also effect performance and could cause problems with remote config)

Sorry for the Issues flood

**Comment by UnamSanctam** [comment]
No it's good, they are reasonable questions.
