### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/UnamWebPanel#17]
Hello! Everything works like a charm and it's up and running, I'm just wondering about where it says "Status" on the web panel. What do the different statuses mean? Like "Stopped". Also, will the miners who didn't have the system requirements to mine show up on the list? 

I also just want to thank you for developing this!

**Comment by UnamSanctam** [comment]
"Stopped" means that it has stopped mining for whatever reason, this status isn't very common. "Active" means that it's ready to mine and tries to mine and "Active (Idle)" means that it's ready to mine and tries to use the "Idle GPU" amount of GPU (if enabled). It's possible that it can show 0H/s while active if the GPU doesn't have enough VRAM (not enough empty due to being used or if the model doesn't have enough VRAM). Then there is the "Paused (Stealth)" status which appears when the miner is paused due to any program from the "Stealth Targets" being open. There is the "Offline" status which just appears if the miners last connection to the web panel was longer than 5 minutes ago. Lastly there is the "Unknown" status which will only appear if the web panel has no idea what happened, though this shouldn't really appear.

The miners will show up if they have a CPU/GPU (and the GPU drivers are new enough), the only reason the GPU (ethminer) miner wouldn't appear is if the drivers are too old or if they have no GPU. If they just have too little VRAM left or just overall then it will still show in the panel while it's waiting.
