### ISSUE TITLE
[QUESTION] Why do I have only 5KH/s?

### ISSUE THREAD

**Issue by kasperinjo** [UnamSanctam/UnamWebPanel#171]
Hi, I got 5KH/s on GPU NVIDIA GeForce RTX 2060 and AMD CPU Ryzen 5 3600 6-Core Processor. I have put that it works on 100%, but still nothing. I closed all programs too. I am mining monero xmrig version 2.5.0 via xmr.2miners.com:12222. Is there any other cryptocurrency that I could mine and get more from my PC set?

**Comment by UnamSanctam** [comment]
Monero is a CPU coin (uses the RandomX algorithm) so mining it with a GPU isn't very profitable, you should probably mine a GPU coin like ETH or ETC to get the most out of your GPU and then only mine Monero on the CPU. Your CPU should get around 5 KH/s when mining Monero but it can also be a bit lower since your computer (probably) isn't optimized for mining and it won't use everything to avoid causing lag. You can make it ignore that and force it to use all CPU (something like the `--cpu-no-yield` command in "Advanced Arguments") but it's not really recommended, you should also start it as administrator if you aren't already since that will increase the hashrate.

**Comment by kasperinjo** [comment]
Hi, thanks for the big answer. I am using rx/0 algorithm, does that change anything?

**Comment by UnamSanctam** [comment]
Yes that's the RandomX algorithm, it's a CPU algorithm that's designed to be bad on GPUs so it's best to also add a GPU coin miner if you want to mine with the GPU as well and not just the CPU. If you get 5 KH/s with rx/0 with just your CPU then that's about the expected hashrate from your CPU.

**Comment by kasperinjo** [comment]
Can I use etc.2miners.com for ETC for binance wallet?

**Comment by kasperinjo** [comment]
I am assuming that etc also uses GPU

**Comment by UnamSanctam** [comment]
Yes that would work, ETC is a GPU only coin so yes it will use your GPU.

**Comment by kasperinjo** [comment]
Ooh, is there a coin that uses both GPU and CPU? Thanks for fast answers, I appreciate that :D

**Comment by kasperinjo** [comment]
And what what should I type in pastebin for "algo": "rx/0", if using ETC?

**Comment by UnamSanctam** [comment]
> Ooh, is there a coin that uses both GPU and CPU? Thanks for fast answers, I appreciate that :D

Not really any very profitable one, because the CPUs have to compete with the GPUs which they usually can't. Which is why CPU algorithms are specifically created to be bad for GPUs (and ASICs). Usually you would run two miners, one for CPU mining and one for GPU mining for maximum profitability.

>And what what should I type in pastebin for "algo": "HERE", if using ETC? Also, for settings on the website, should I use "ethminer", "xmrig" or "none" if mining ETC?

For ETH/ETC/UBQ the configuration should be formatted like this:
https://pastebin.com/raw/rCQQyJSW, you can also open your ETC builder in the miner and press the JSON tab to get a JSON configuration of your settings directly. The ETH/ETC/UBQ miner is a completely different miner than the XMR miner so you have to compile the miner with an ETH/ETC/UBQ miner added since otherwise it won't add those files (to save space). So you can't change an RandomX (Monero) miner to an Etchash (Ethereum Classic) miner and vice-versa because they are two different sorts of miners.

Monero (RandomX) is mined with xmrig and Ethereum Classic (Etchash) is mined with ethminer so for ETC use the "ethminer" configuration.

**Comment by kasperinjo** [comment]
I understand, thanks!
