### ISSUE TITLE
Remote Configuration URL

### ISSUE THREAD

**Issue by hey000hey** [UnamSanctam/UnamWebPanel#203]
What do I put for the Remote Configuration URL? I know you can link it to the web panel somehow, but do I put the same url as the website? (/api/endpoint.php/)?

**Comment by UnamSanctam** [comment]
For the "Remote Configuration URL" you would enter the URL to the page containing the JSON code, for example https://rentry.co/39ofx/raw. You wouldn't really use the web panel for the "Remote Configuration" since you can already change the configuration of miners inside the web panel itself by using the "Configurations" tab and then applying the configuration you want to a miner in the list (or change the default configurations).

**Comment by hey000hey** [comment]
thanks! so even if I turn "remove configuration" off, I will still be able to change the config using the web panel, yes?

**Comment by UnamSanctam** [comment]
Yes that's correct.
