### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by floof989763** [UnamSanctam/UnamWebPanel#213]
Is having your personel website, web server and domain necessory to run the web panel ? If no please explain how to do so?

**Comment by UnamSanctam** [comment]
A webserver yes, either use a webhost online or host one yourself (behind something like a VPN or on a VPS). A domain isn't necessary though a bulletproof domain would help of course, since if the website IP changes then you can change it in the domain, and if you were to use some online webhost then if you get banned then you can change what the domain points to.
