### ISSUE TITLE
Panel error

### ISSUE THREAD

**Issue by Xeneht** [UnamSanctam/UnamWebPanel#221]
I use the panel since the last update, but now the miners page can't load
![image](https://user-images.githubusercontent.com/99096857/210377090-ade54238-2943-48aa-a437-dc39e70ce5f9.png)

On the error.log:
[03-Jan-2023 14:23:47 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 10 disk I/O error in /customers/1/b/0/mywebsite.com/httpd.www/dashboard/internalPages/minersAjax.php:8
Stack trace:
#0 /customers/1/b/0/mywebsite.com/httpd.www/dashboard/internalPages/minersAjax.php(8): PDO->query('SELECT hr_algor...')
#1 /customers/1/b/0/mywebsite.com/httpd.www/dashboard/page-loader.php(5): include('/customers/1/b/...')
#2 {main}
  thrown in /customers/1/b/0/mywebsite.com/httpd.www/dashboard/internalPages/minersAjax.php on line 8

Idc if i need to setup the website again, besides I'm trying to modify the 2miners settings and i need a worker ip, but the ips are not updated because i have tried with 4 different workers and no one works. I'm submiting the worker ip they request so i don't know if it's a website/miner error or this feature is not added
![image](https://user-images.githubusercontent.com/99096857/210377964-ab523b20-7b82-4f05-98de-1755fa2b2dc6.png)

**Comment by UnamSanctam** [comment]
The IPs on the web panel are correct (they are taken directly from the connection) so if you're sure that you're entering the correct IP that 2miner wants then it's because of something on their end. But make sure that you're entering the IP of that specific worker that they want. Could also be that it's connecting to the pool with IPv6 but connecting to the web panel with IPv4 though I don't think that's the case (not that there's anything that could be done about that if that's the case anyways).
