### ISSUE TITLE
how can fix ip

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/UnamWebPanel#236]
how can fix ip showin with ngrok service its appear ::1 is IP

**Comment by UnamSanctam** [comment]
Since all the connections that your PHP receives comes from the ::1 IP you will have to get the original IP from what ngrok tells you it is, sometimes those kinds of tunneling services adds the original IP into the call under the name `X-Forwarded-For` or similarly named headers.
So you could try replacing `REMOTE_ADDR` here to `X-Forwarded-For` and it might work:
https://github.com/UnamSanctam/UnamWebPanel/blob/b8b30b7b0412fa2f817fb80df9b561291eddb186/UnamWebPanel/api/endpoint.php#L13

**Comment by tarekxxx** [comment]
greeat bro iam going to test it <3 thanks for helping mate
