### ISSUE TITLE
Statistics Panel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#237]
Good afternoon Unam. Can you please tell me how to turn off the statistics panel? I just don't use it.
Just delete the folder - internalPages? Or do I need to edit some more code?

**Comment by UnamSanctam** [comment]
Why would you need to delete it (or turn it off), you just don't need to open the page if you don't want to see it.

**Comment by masterjek** [comment]
I thought statistics creates an additional load on the site? Or I'm wrong?

**Comment by UnamSanctam** [comment]
No, the statistics page just quickly reads the database whenever you open it and uses no additional resources beyond that. The hashrate history does increase load though since it needs to insert and remove records on each API call, if you want to disable that if you haven't already then there's an option inside `config.php`.

**Comment by masterjek** [comment]
Sorry for the bother, I'll ask in this thread so as not to open a new one. I have now completely disabled the site, the web panel does not work. It's been 10 minutes since the site stopped. But almost all workers continue to work on the configuration from the web panel. I did not set remote configurations.
I made this function in DNS - Purge Cache
Clear cached files to force Cloudflare to fetch a fresh version of those files from your web server. You can purge files selectively or all at once.
Note: Purging the cache may temporarily degrade performance for your website and increase load on your origin.
I'm wondering where the workers continue to take the configuration from the web panel if it is stopped?

**Comment by UnamSanctam** [comment]
They will continue to run with that configuration until they restart (or receive a new one from the web panel), since if it was programmed otherwise then if the web panel (or "Remote Configuration") were to go down temporarily then it would revert the configuration which might not be a working or desirable one. Allowing interruptions without reverting the configuration is necessary since websites are not guaranteed to always be up.

If you only have the web panel and no "Remote Configuration" then there are currently two pool configurations in it:
1) Web Panel Configuration
2) Builder Configuration

If the web panel pool configuration stops working then it will cycle to the builder configuration, and then retry the web panel configuration after while since it preferably wants to be as far up in the list as possible because they have higher priority.

**Comment by masterjek** [comment]
Thank you very much
