### ISSUE TITLE
Add auto-update to panel like wordpress

### ISSUE THREAD

**Issue by suckma420** [UnamSanctam/UnamWebPanel#3]

**Comment by UnamSanctam** [comment]
Well, the panel doesn't really have a central authority unlike Wordpress so I don't know who well that would work, especially since not everyone places their files in the same place and structure as it is shipped with.

To update the panel all you really have to save it the unamwebpanel.db. So you can remove all files except unamwebpanel.db, then download the new panel and upload that, then replace the unamwebpanel.db with the one you saved from your previous version. Then change the password in config.php and you're done.

**Comment by suckma420** [comment]
Hmm, what about making it a wordpress theme/plugin? That's sounds cool

**Comment by UnamSanctam** [comment]
The panel? That wouldn't really be possible due to how it works.
