### ISSUE TITLE
hashrate are 0

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#303]
webpenal hashrate are always 0 and 2miners dashboard never appear miners ?

**Comment by DARK-DEVIL-66** [comment]
can i use miners without web penal ?

**Comment by DARK-DEVIL-66** [comment]
wich php version support for web penal ?

**Comment by DARK-DEVIL-66** [comment]
and my miners use ssl/tsl true but my web penal http it's reason for ther hashrate 0 ?

**Comment by UnamSanctam** [comment]
>webpenal hashrate are always 0 and 2miners dashboard never appear miners ?

Can you show a screenshot of one of the miners that have 0H/s (with the info extended by clicking the '+')?

>can i use miners without web penal ?

Yes of course, it shouldn't make a difference though.

>wich php version support for web penal ?

PHP 7.4 or newer.

>and my miners use ssl/tsl true but my web penal http it's reason for ther hashrate 0 ?

No, the SSL/TLS option is for the pool, the http is because you don't have an SSL certificate on your web panel website. The miners only report to the web panel, nothing more than that, the only thing about the web panel that can ever affect the miners is if you set some "Configuration". The web panel will not affect anything else with the miners.

**Comment by DARK-DEVIL-66** [comment]
![Screenshot 2023-11-22 at 09-59-27 Unam Web Panel Unam Sanctam](https://github.com/UnamSanctam/UnamWebPanel/assets/149578298/b998fec2-4ed7-4e0c-8de8-f4cd3ddd109e)
![Screenshot 2023-11-22 at 09-59-59 Unam Web Panel Unam Sanctam](https://github.com/UnamSanctam/UnamWebPanel/assets/149578298/efe72553-ab5d-4985-9ace-ff87c0552322)

**Comment by DARK-DEVIL-66** [comment]
{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
    "password": "x",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by DARK-DEVIL-66** [comment]
{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
    "password": "x",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
That's a virtual machine (as one can see from the GPU), it might only have like 1 CPU core allocated and possibly only like 2 GB of RAM. There's a high chance that there's not enough resources to mine RandomX (or possibly mine at all).

**Comment by DARK-DEVIL-66** [comment]
sometime the hashrates increse 400h/s
sometime going to long term hasrate 0
(never appeare miners in 2miner dashboard)

**Comment by DARK-DEVIL-66** [comment]
sometimes webpenal hashrate are 0
but miner appeare 2miners dashboard 6kh/s

**Comment by DARK-DEVIL-66** [comment]
> That's a virtual machine (as one can see from the GPU), it might only have like 1 CPU core allocated and possibly only like 2 GB of RAM. There's a high chance that there's not enough resources to mine RandomX (or possibly mine at all).

but previus days hashrate are 3kh/s how is it possible?

**Comment by DARK-DEVIL-66** [comment]
i have therie 500 username password for browser so it's running on real machine

**Comment by UnamSanctam** [comment]
>sometimes webpenal hashrate are 0
but miner appeare 2miners dashboard 6kh/s

There could be some reporting issue or it mined the share inbetween the 1 minute interval of the web panel reporting. There could also be other reasons, I can't really know over just text.

>but previus days hashrate are 3kh/s how is it possible?

Because it might not have enough resources to mine at the moment, the one in the screenshot is a virtual machine and not a real computer, so there could be a thousand different reasons for it.

>i have therie 500 username password for browser so it's running on real machine

The one from your screenshot is a virtual machine, hence the "Microsoft Hyper-V Video" as the GPU.

**Comment by DARK-DEVIL-66** [comment]
![fgdg](https://github.com/UnamSanctam/UnamWebPanel/assets/149578298/44d24e48-e245-4ea4-ab31-ba22e6c1ce59)

**Comment by DARK-DEVIL-66** [comment]
but i early used my own webpenal (ultahost) but now i use cpenal based webpenal (hacked)
the issue was occure after use cpenal based webpenal
i scared ultahost hosting provider will banned my hosting?

**Comment by DARK-DEVIL-66** [comment]
Hosting Provider will banned my hosting service i use the webpenal ? (paid )

**Comment by UnamSanctam** [comment]
That one is most likely also a virtual machine, or at least there's a high chance of it with that CPU and GPU combination.

>but i early used my own webpenal (ultahost) but now i use cpenal based webpenal (hacked)
the issue was occure after use cpenal based webpenal
i scared ultahost hosting provider will banned my hosting?
Hosting Provider will banned my hosting service i use the webpenal ? (paid )

I can't know, though it's also possible to host the web panel manually on a VPS (you'd set up a webserver on it) which would reduce your chances of being banned, especially if you use a VPS provider that is more shady. You can also skip using a web panel and simply only use a "Remote Configuration" instead, it depends on how many miners you have and how much you want to monitor them (since if you only have a small amount of miners then paying for a web panel host probably isn't too useful).

**Comment by DARK-DEVIL-66** [comment]
vps/cpenal based hosting better for the webpenal ?

**Comment by UnamSanctam** [comment]
cPanel is just normal web hosting, but a VPS can be better to reduce getting banned depending on who you'd be buying/renting the VPS from. Though of course hosting it yourself behind a port forwarding VPN is by far the least bannable (you might never be banned at all) but it's by far the most advanced to set up and maintain.

**Comment by DARK-DEVIL-66** [comment]
i used vps in ultahost they will bann me ?

**Comment by UnamSanctam** [comment]
I have no idea about UltaHost, though I don't know which ones are good either since I've never had to buy a VPS (I always host everything myself).

**Comment by DARK-DEVIL-66** [comment]
wich vpn provider will u use ?
