### ISSUE TITLE
My Question 

### ISSUE THREAD

**Issue by DumbStackz4L** [UnamSanctam/UnamWebPanel#381]
Sorry if I message a lot I am not sure if you saw it but i also commented "
I just want the silent miner that you created to still run even when a user's computer has been shutdown or in sleep mode. I'm not good at coding but i think that even if you added a .bat that could run these commands and add some registry stuff to have it run while in sleep mode/shutdown that would be awesome. I know that this may be challenging. But I am grateful for you trying you're very good at what you do. (You could even have the whole computer running i just want the physical appearance of the computer off. If that makes sense sorry if I am bad at explaining)" Also I was wondering a eta estimate on how long this would take you.

**Comment by alcinzal** [comment]
Sadly I don't think that this will be implemented. I am sure it is possible, and I have no idea if it is easy or difficult to do, but as Unam mentioned in your previous issue, it would probably be a massive project.

And even if Unam implemented this and got it working, most users will understand that their computers are actually not off, because when you turn off a computer, it stops making sounds, fans go off, hard drives stop, etc. However if you implement this, the computer would still be on, making noises. I highly doubt that this feature would really be that beneficial, it might even cause users to factory reset their computer because they think something is wrong with it.
