### ISSUE TITLE
When are you gonna add password recovery?

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/UnamWebPanel#7]
And when you do will you receive the logs to the webpanel or email?

**Comment by UnamSanctam** [comment]
What? Why would you ever need password recovery? Just check the config.php. 

What do you mean by "receive the logs to the webpanel or email"? Do you mean the miner logs themselves, as in all the console data that appears? If so then never since that would be a huge amount of traffic.

**Comment by Brainshot** [comment]
> 
> 
> What? Why would you ever need password recovery? Just check the config.php.
> 
> What do you mean by "receive the logs to the webpanel or email"? Do you mean the miner logs themselves, as in all the console data that appears? If so then never since that would be a huge amount of traffic.

No i thought you were adding a stealer, what did you mean by that? 

i was talking about password recovery that sends all browsers info to the webpanel or email

**Comment by UnamSanctam** [comment]
Oh that's what you mean, I still have to create most of the stealer (will be a separate program probably called UnamStealer), I haven't had any time to code since the release of the miner since I have helped people non-stop since then. And even then I'm going to update the UnamBinder and UnamDownloader programs first before that, but the Stealer will probably send the things through either Discord Webhooks (although I dislike them) or the Web Panel (will definitely be supported).

**Comment by Brainshot** [comment]
> 
> 
> Oh that's what you mean, I still have to create most of the stealer (will be a separate program probably called UnamStealer), I haven't had any time to code since the release of the miner since I have helped people non-stop since then. And even then I'm going to update the UnamBinder and UnamDownloader programs first before that, but the Stealer will probably send the things through either Discord Webhooks (although I dislike them) or the Web Panel (will definitely be supported).

Alright thanks
